version: '3'

services:
  nginx:
    image: nginx:1.25.2
    ports:
      - 9001:80
    depends_on:
      - web
    volumes:
      - src-dir:/app
      - static-assets:/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  web:
    build: .
    depends_on:
      - mariadb
      - memcached
      - redis
    volumes:
      - src-dir:/app
      - static-assets:/static
  mariadb:
    image: mariadb:10.11.5
    environment:
      MARIADB_ROOT_PASSWORD: password
  memcached:
    image: memcached:1.6.21
  redis:
    image: redis:7.2.1

volumes:
  src-dir:
  static-assets:
